### PR TITLE
fix: add some deadzone for joypad motion detection

### PR DESCRIPTION
**Pull request by raganw**
Prior to this change, if there was both a keyboard and joypad connected and the user was using the keyboard, but there was some stick drift with the joypad, input detection would bounce between keyboard and joypad.

This change adds a minimum axis_value that a InputEventJoypadMotion must have before detecting the input type as a joypad.

Ideally, it seems like this deadzone should be configurable, but I'm new to Godot and its plugin architecture and couldn't quite figure out how best to surface that as customizable.

### CODE REVIEW

**Comment by Pennycook** [comment]
Thanks for working on this.  I didn't see this behavior with my controllers, so I didn't realize this could be a problem.

> Ideally, it seems like this deadzone should be configurable, but I'm new to Godot and its plugin architecture and couldn't quite figure out how best to surface that as customizable.

I'm not sure what the best way to do this is, either.  For now, what I'd recommend is declaring a new variable in `InputPromptManager`, similar to what I did for `preferred_icons`:

https://github.com/Pennycook/godot-input-prompts/blob/c49406902733901419f4d8accabf48d3bb6b0b00/addons/input_prompts/input_prompt_manager.gd#L35-L45

If there was something like a `device_detection_deadzone` variable, then there would at least be an easy way to modify this value through code.

**Comment by Pennycook** [comment]
I've been looking at this a bit more recently, and discovered two things of interest:
1) Godot uses a deadzone value of 0.5 by default (see [here](https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html#dead-zone))
2. It is possible to add custom entries into the ProjectSettings

I still need to figure out exactly how to do this, but ProjectSettings seems like the right place to expose an InputPrompt-specific deadzone value.

**Comment by Pennycook** [comment]
@raganw: I think I got this working with ProjectSettings, so the value is configurable without touching any of the plugin code. See below:

image

I tested this on my Steam Deck (which, it turns out, has a small amount of stick drift!) and things seem to work.  But I'd appreciate it if you could take a look and confirm that everything is working as expected before I merge it in.

**Comment by raganw** [comment]
@Pennycook - Thanks for shepherding this change. I confirmed that this works with the project I was working on and it looks good. I merged in `main` so if you're good with it, :shipit:

**Review by Pennycook — APPROVED** [review]

**Comment by Pennycook** [comment]
You're very welcome. Thank you for identifying the issue, providing the fix, and for helping out with testing.

It's merged! :tada:

**Pull request merged**
